Last edits
ted7007/Contacts pull request #2
Opened 2022-07-03 06:30 UTC by ted7007

Added auto-mapper to project

2022-07-03 06:35 UTC, EvoMGenius requested changes

2022-07-03 06:35 UTC, EvoMGenius commented on Contacts/Controller/PersonController.cs
>          private IPersonService db;
почему db?

2022-07-11 11:00 UTC, EvoMGenius requested changes
Поменяй везде в дто и в сущности VKLink на vkLink. на фронте проблемы кое-какие из-за этого

2022-07-11 11:07 UTC, EvoMGenius approved these changes
если то ч то я выделил никак не повлияет. то можешь сливать.

2022-07-11 11:07 UTC, EvoMGenius commented on ContactsTests/ControllerTests/MapperTests/PersonMapperTests.cs
> +                VKLink = "abc",
это никак не повлияет?

2022-07-11 11:07 UTC, EvoMGenius commented on ContactsTests/ControllerTests/MapperTests/PersonMapperTests.cs
> +                VKLink = "abc",
и это?

2022-07-11 11:46 UTC, ted7007 commented
тесты залил случайно, ну да ладно(

2022-07-11 11:46 UTC, merged